In [3]:
import numpy


In [4]:
world_alcohol=numpy.genfromtxt("t.txt",delimiter=",",dtype=str)
print(type(world_alcohol))

<class 'numpy.ndarray'>


In [5]:
world_alcohol

array([['1', '0.6309556547829342'],
       ['8', '0.617754249513818'],
       ['17', '0.3497269770579191'],
       ['20', '0.3004097139244665'],
       ['33', '0.6243577872121011'],
       ['34', '0.626206179585381'],
       ['35', '0.5093653595516284'],
       ['36', '0.4857022953373795'],
       ['37', '0.3934475922484621'],
       ['38', '0.644644645353909'],
       ['45', '0.5153755926877271'],
       ['50', '0.6525271394667116'],
       ['55', '0.6906524817773899'],
       ['60', '0.6877337035960143'],
       ['66', '0.6630383325619976'],
       ['67', '0.627809993943242'],
       ['71', '0.6199617663901186'],
       ['80', '0.66921699035322'],
       ['85', '0.6555048305868467'],
       ['86', '0.4246472825965197'],
       ['95', '0.4163592442193223'],
       ['104', '0.6502538871348517'],
       ['113', '0.6491093352463818'],
       ['123', '0.6388544188499368'],
       ['126', '0.3253610901747978'],
       ['133', '0.4201360599020867'],
       ['141', '0.6593952690517892'],
   

In [6]:
print (help(numpy.genfromtxt))

Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings in Python 3k.  The strings
        in a list or 

In [7]:
vector=numpy.array([5,10,15,20])

In [8]:
matrix=numpy.array([[5,10,15],[20,25 ,30],[35,40,45]])

In [9]:
print(vector)

[ 5 10 15 20]


In [10]:
print(matrix)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [11]:
print(vector.shape)

(4,)


In [12]:
print(matrix.shape)

(3, 3)


In [13]:
numbers=numpy.array(['1',2,3,4])


In [14]:
print(numbers)
numbers.dtype

['1' '2' '3' '4']


dtype('<U1')

In [15]:
world_alcohol


array([['1', '0.6309556547829342'],
       ['8', '0.617754249513818'],
       ['17', '0.3497269770579191'],
       ['20', '0.3004097139244665'],
       ['33', '0.6243577872121011'],
       ['34', '0.626206179585381'],
       ['35', '0.5093653595516284'],
       ['36', '0.4857022953373795'],
       ['37', '0.3934475922484621'],
       ['38', '0.644644645353909'],
       ['45', '0.5153755926877271'],
       ['50', '0.6525271394667116'],
       ['55', '0.6906524817773899'],
       ['60', '0.6877337035960143'],
       ['66', '0.6630383325619976'],
       ['67', '0.627809993943242'],
       ['71', '0.6199617663901186'],
       ['80', '0.66921699035322'],
       ['85', '0.6555048305868467'],
       ['86', '0.4246472825965197'],
       ['95', '0.4163592442193223'],
       ['104', '0.6502538871348517'],
       ['113', '0.6491093352463818'],
       ['123', '0.6388544188499368'],
       ['126', '0.3253610901747978'],
       ['133', '0.4201360599020867'],
       ['141', '0.6593952690517892'],
   

In [16]:
print(matrix[:,1])

[10 25 40]


In [17]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
print(matrix[1:3,0:2])

[[20 25]
 [35 40]]


In [19]:
vector


array([ 5, 10, 15, 20])

In [20]:
vector==10

array([False,  True, False, False], dtype=bool)

In [21]:
a=vector==10


In [22]:
a


array([False,  True, False, False], dtype=bool)

In [23]:
vector


array([ 5, 10, 15, 20])

In [24]:
equal_to_ten_or_five=(vector==10)|(vector==5)
print(equal_to_ten_or_five)

[ True  True False False]


In [25]:
vector[equal_to_ten_or_five]=50

In [45]:
vector

array([50, 50, 15, 20])

In [46]:
print(vector)

[50 50 15 20]


In [47]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [48]:
second_column_25=matrix[:,1]==25

In [49]:
second_column_25

array([False,  True, False], dtype=bool)

In [50]:
matrix[second_column_25,1]=10

In [51]:
print(matrix)

[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [52]:
vector=numpy.array(["1","2","3"])

In [53]:
print(vector.dtype)

<U1


In [54]:
print(vector)

['1' '2' '3']


In [55]:
vector=vector.astype(float)

In [56]:
print(vector)

[ 1.  2.  3.]


In [57]:
print(vector.dtype)

float64


In [58]:
vector.min()

1.0

In [59]:
vector.max()

3.0

In [60]:
vector.mean()

2.0

In [61]:
matrix=numpy.array([
    [5,10,15],
    [20,25,30],
    [35,40,45]
])

In [62]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [63]:
matrix.sum(axis=0)

array([60, 75, 90])

In [64]:
numpy.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
range(15)==numpy.arange(15)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [68]:
print(numpy.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [69]:
a=numpy.arange(15)

In [72]:
a=a.reshape(3,5)

In [73]:
a.shape

(3, 5)

In [74]:
a.dtype.name

'int32'

In [75]:
a.ndim

2

In [76]:
a.size

15

In [77]:
numpy.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [78]:
numpy.zeros((3,4)).ndim

2

In [79]:
numpy.ones((2,3,4))

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])

In [80]:
numpy.arange(10,30,5)

array([10, 15, 20, 25])

In [81]:
a=numpy.arange(12)

In [82]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
numpy.random.random((2,3))

array([[ 0.36189354,  0.74370328,  0.30022774],
       [ 0.41056536,  0.06740426,  0.66881868]])

In [84]:
from numpy import pi

In [85]:
numpy.linspace(0,2*pi,100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [86]:
numpy.linspace(0,2*pi,10)

array([ 0.        ,  0.6981317 ,  1.3962634 ,  2.0943951 ,  2.7925268 ,
        3.4906585 ,  4.1887902 ,  4.88692191,  5.58505361,  6.28318531])

In [87]:
a=numpy.array([20,30,40,50])

In [88]:
b=numpy.arange(4)

In [89]:
print(a)

[20 30 40 50]


In [90]:
print(b)

[0 1 2 3]


In [91]:
c=range(4)

In [92]:
a-b

array([20, 29, 38, 47])

In [93]:
a-c

array([20, 29, 38, 47])

In [94]:
a+c

array([20, 31, 42, 53])

In [95]:
a*c

array([  0,  30,  80, 150])

In [97]:
a.size

4

In [98]:
a

array([20, 30, 40, 50])

In [99]:
a**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [100]:
a**3

array([  8000,  27000,  64000, 125000], dtype=int32)

In [101]:
a=numpy.floor(10*numpy.random.random((3,4)))

In [102]:
print(a)

[[ 5.  2.  0.  5.]
 [ 7.  6.  4.  3.]
 [ 6.  1.  2.  4.]]


In [104]:
print(a.ravel())

[ 5.  2.  0.  5.  7.  6.  4.  3.  6.  1.  2.  4.]


In [105]:
a

array([[ 5.,  2.,  0.,  5.],
       [ 7.,  6.,  4.,  3.],
       [ 6.,  1.,  2.,  4.]])

In [106]:
a.T

array([[ 5.,  7.,  6.],
       [ 2.,  6.,  1.],
       [ 0.,  4.,  2.],
       [ 5.,  3.,  4.]])

In [111]:
a.shape=(1,12)

In [112]:
a

array([[ 5.,  2.,  0.,  5.,  7.,  6.,  4.,  3.,  6.,  1.,  2.,  4.]])

In [113]:
a.shape=(6,2)

In [114]:
a

array([[ 5.,  2.],
       [ 0.,  5.],
       [ 7.,  6.],
       [ 4.,  3.],
       [ 6.,  1.],
       [ 2.,  4.]])

In [118]:
a.reshape(2,-1)

array([[ 5.,  2.,  0.,  5.,  7.,  6.],
       [ 4.,  3.,  6.,  1.,  2.,  4.]])

In [119]:
a

array([[ 5.,  2.],
       [ 0.,  5.],
       [ 7.,  6.],
       [ 4.,  3.],
       [ 6.,  1.],
       [ 2.,  4.]])

In [122]:
numpy.vstack((a,a))

array([[ 5.,  2.],
       [ 0.,  5.],
       [ 7.,  6.],
       [ 4.,  3.],
       [ 6.,  1.],
       [ 2.,  4.],
       [ 5.,  2.],
       [ 0.,  5.],
       [ 7.,  6.],
       [ 4.,  3.],
       [ 6.,  1.],
       [ 2.,  4.]])

In [123]:
a=numpy.floor(10*numpy.random.random((2,12)))

In [124]:
print(a)

[[ 0.  5.  2.  0.  3.  0.  1.  8.  5.  3.  5.  3.]
 [ 9.  1.  0.  3.  6.  9.  5.  6.  9.  4.  6.  6.]]


In [125]:
print(numpy.hsplit(a,3))

[array([[ 0.,  5.,  2.,  0.],
       [ 9.,  1.,  0.,  3.]]), array([[ 3.,  0.,  1.,  8.],
       [ 6.,  9.,  5.,  6.]]), array([[ 5.,  3.,  5.,  3.],
       [ 9.,  4.,  6.,  6.]])]


In [126]:
a

array([[ 0.,  5.,  2.,  0.,  3.,  0.,  1.,  8.,  5.,  3.,  5.,  3.],
       [ 9.,  1.,  0.,  3.,  6.,  9.,  5.,  6.,  9.,  4.,  6.,  6.]])

In [128]:
print(numpy.hsplit(a,(3,4)))

[array([[ 0.,  5.,  2.],
       [ 9.,  1.,  0.]]), array([[ 0.],
       [ 3.]]), array([[ 3.,  0.,  1.,  8.,  5.,  3.,  5.,  3.],
       [ 6.,  9.,  5.,  6.,  9.,  4.,  6.,  6.]])]


In [129]:
b=a

In [130]:
print(a is b)

True


In [132]:
print(str(id(a))+","+str(id(b)))

129598048,129598048


In [133]:
b=a.view()

In [134]:
print(a is b)

False


In [135]:
import numpy as np

In [140]:
#求矩阵的每列的最大值
data=np.sin(np.arange(20).reshape(5,4))

In [141]:
print (data)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [142]:
ind=data.argmax(axis=0)

In [143]:
print(ind)

[2 0 3 1]


In [144]:
data_max=data[ind,range(data.shape[1])]
print(data_max)

[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [146]:
a=np.arange(0,40,10)
print(a)
b=np.tile(a,(4,3))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [147]:
a=np.array([[4,3,5],[1,2,1]])
print(a)

[[4 3 5]
 [1 2 1]]


In [148]:
b=np.sort(a,axis=1)
print(b)

[[3 4 5]
 [1 1 2]]


In [149]:
a.sort(axis=1)
print(a)

[[3 4 5]
 [1 1 2]]


In [150]:
a=np.array([4,3,1,2])
j=np.argsort(a)
print(j)
print("------")
print(a[j])

[2 3 1 0]
------
[1 2 3 4]
